<?php

/**
 * @file
 * This module is the base modules for site testing.
 */

use Bluecadet\DrupalPackageManager\Checker;
use Drupal\update\UpdateManagerInterface;

/**
 * Implements hook_theme().
 */
function external_site_monitor_theme() {
  return [
    'content_edit_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function external_site_monitor_page_attachments_alter(array &$page) {
  // Attaches css assets globally.
  $user = \Drupal::currentUser();
  if ($user->hasPermission('access toolbar')) {
    $page['#attached']['library'][] = 'external_site_monitor/esm_base';
  }
}

/**
 * Implements hook_update_status_alter().
 */
function external_site_monitor_update_status_alter(&$projects) {
  $modules['pingevt'] = [
    'external_site_monitor',
  ];

  $filtered_projects = [];

  foreach ($modules as $user => $user_data) {
    $filtered_projects += array_filter($projects, function($v) use ($user_data) {
        return in_array($v, $user_data);
    }, ARRAY_FILTER_USE_KEY);
  }

  $checker = new Checker($modules, $filtered_projects);

  foreach ($modules as $user => $user_data) {
    foreach ($user_data as $module_name) {
      if (in_array($module_name, array_keys($projects))) {
        $projects[$module_name] = $checker->updateDrupalModulePackage($projects[$module_name], $user, $module_name);
      }
    }
  }
}
