<?php

/**
 * @file
 * Provides a site entity type.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function esm_site_theme() {
  return [
    'site' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for site templates.
 *
 * Default template: site.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the site information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_site(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  $site = $variables['elements']['#site'];
  $variables['attributes']['class'][] = "site";
  $variables['attributes']['class'][] = "site--view-mode-" . Html::cleanCssIdentifier($variables['elements']['#view_mode']);
}
