<?php

/**
 * @file
 * Provides un/install functionality.
 */

use Drupal\Core\Database\Database;

/**
 * Implements hook_schema().
 */
function esm_test_timing_monitor_schema() {
  return _esm_test_timing_monitor_schemas();
}

/**
 * Custom schema for Timing Monitor tests tables.
 */
function _esm_test_timing_monitor_schemas() {
  $schema = [];

  // Table.
  $schema['esm_tm_daily_data'] = [
    'description' => 'A table to store Timing monitor daily average data.',
    'fields' => [
      'id' => [
        'description' => 'The unique ID',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'result' => [
        'description' => 'The result these results belongs to.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'period' => [
        'description' => '',
        'type' => 'varchar',
        'length' => '20',
        'not null' => TRUE,
      ],
      'average' => [
        'description' => '',
        'type' => 'float',
        'size' => 'normal',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => 0,
      ],
    ],
    'primary key' => ['id'],
    'foreign keys' => [
      'result' => [
        'table' => 'result',
        'columns' => [
          'result' => 'id',
        ],
      ],
    ],
  ];

  return $schema;
}

/**
 * Add esm_tm_daily_data table.
 */
// function esm_test_timing_monitor_update_9001() {

// }
