<?php

/**
 * @file
 * Functions and hooks for handling the Cache Hit Ratio test.
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Link;
use Drupal\Core\Render\Markup;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function esm_test_timing_monitor_theme() {
  return [
    'site_test_results__tm_test' => [
      'variables' => [
        'test' => NULL,
        'title' => "",
        'content' => [],
      ],
      'base hook' => 'site_test_results',
    ],
    'result__tm_test_result' => [
      'base hook' => 'result',
    ],
  ];
}

/**
 * Implements hook_preprocess_THEME().
 */
function esm_test_timing_monitor_preprocess_site_test_results__tm_test(&$variables) {

  foreach ($variables['content']['data'] as &$url_group) {
    if (isset($url_group['#attributes'])) {
      $url_group['attributes'] = new Attribute($url_group['#attributes']);
    }
    else {
      $url_group['attributes'] = new Attribute();
    }

    foreach ($url_group['group'] as &$table_grp) {
      if (isset($table_grp['#attributes'])) {
        $table_grp['attributes'] = new Attribute($table_grp['#attributes']);
      }
      else {
        $table_grp['attributes'] = new Attribute();
      }
    }
  }

  // Add in libraries.
  $variables['libraries']['#attached']['library'][] = 'esm_test_timing_monitor/tm_results';
}

/**
 * Implements hook_preprocess_result().
 */
function esm_test_timing_monitor_preprocess_result(&$variables) {

  $result = $variables['elements']['#result'];
  $view_mode = $variables['elements']['#view_mode'];

  if ($result->bundle() == "tm_test_result" && $view_mode == "full") {

    // Set up chart.
    $runnerManager = \Drupal::service('plugin.manager.esm_test_runner');
    $test = $result->test->entity;
    $plugin_id = "tm_test_runner";
    $runner = $runnerManager->createInstance($plugin_id);
    $variables['chart'] = $runner->getDataChart($test, 30);


    $table = [
      '#type' => "table",
      '#caption' => "Average Execution Times",
      '#attributes' => ['class' => ["tm-results-full"]],
      '#header' => [
        "Period",
        "Average Execution Times",
        "7 day running",
        "30 day running",
      ],
      '#rows' => [],
      '#empty' => t('No content has been found.'),
    ];

    $rows = [];
    list(
      $period,
      $average,
      $running7_ratios,
      $running30_ratios,
    ) = $runner->getData($test);

    foreach ($period as $i => $p) {
      $rows[] = [
        $period[$i],
        number_format($average[$i], 6),
        ($running7_ratios[$i]) ? number_format($running7_ratios[$i], 6) : "-",
        ($running30_ratios[$i]) ? number_format($running30_ratios[$i], 6) : "-",
      ];
    }

    $table['#rows'] = array_reverse($rows);
    $variables['table'] = $table;

    // Attach Library.
    $variables['libraries']['#attached']['library'][] = "esm_test_timing_monitor/tm_results";
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function esm_test_timing_monitor_result_presave($entity) {
  esm_test_timing_monitor_update_result($entity);
}

/**
 * Update the Result entity based on saved json Report.
 */
function esm_test_timing_monitor_update_result($entity) {
  if ($entity->bundle() == "tm_test_result") {

    // Grab last 30 days.
    $query = \Drupal::database()->select("esm_tm_daily_data", 'ep');
    $query->fields('ep', []);
    $query->condition('result', $entity->id());
    $query->range(0, 30);
    $query->orderBy('period', 'DESC');
    $exisitng_data = $query->execute()->fetchAll();

    $count7 = 0;
    $count7_sum = 0;
    $count30 = 0;
    $count30_sum = 0;

    foreach ($exisitng_data as $i => $data) {
      if ($i == 0) {
        $entity->field_latest_avg = $data->average;
      }
      if ($i < 7) {
        $count7++;
        $count7_sum += $data->average;
      }
      if ($i < 30) {
        $count30++;
        $count30_sum += $data->average;
      }
    }

    if ($count7 > 0) {
      $entity->field_7_day = ($count7_sum / $count7);
    }
    if ($count30 > 0) {
      $entity->field_30_day = ($count30_sum / $count30);
    }

  }
}
